### ISSUE TITLE
adding/removing comments with ctrl+/ (like html)?

### ISSUE THREAD

**Issue by laggingreflex** [merwan7/sublime-marko#1]
It seems you can't add/remove comments like you could in html file, with ctrl+/

I tried copying over the `Comments.tmPreferences` from HTML syntax, but I guess it's not that simple

It'd be nice to have commenting support, please consider this feature request!

**Comment by merwan7** [comment]
Sorry for the delay on this. I have finally fixed this issue, thanks for bringing it up. It should be in packagecontrol soon.
