### ISSUE TITLE
Highlighting issue using concise syntax with multiline

### ISSUE THREAD

**Issue by kjs3** [merwan7/sublime-marko#5]
This picture basically says it all. Let me know if this isn't an obvious fix and I can dig into the code.

The template outputs the correct HTML. This is just a highlighting issue.

<img width="1177" alt="index_marko_ _itbe" src="https://cloud.githubusercontent.com/assets/91996/24025634/cfb566d0-0a78-11e7-8099-a5f2e911ac40.png">

**Comment by merwan7** [comment]
Thanks for the picture. It really does say it all 👍  I'll take a look and see what's going on.

**Comment by merwan7** [comment]
Closed this issue as the specific problem noticed is fixed now, but  it revealed an underlying issue which is captured here: https://github.com/marko-js/marko-tmbundle/issues/4  Will continue working on this to see if we can find a solution, but please upgrade the package to fix your specific scenario.  Thanks for finding & reporting it!
